// Code generated by protoc-gen-micro. DO NOT EDIT.
// source: proto/store/store.proto

package go_micro_storeservice

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

import (
	context "context"
	client "github.com/micro/go-micro/client"
	server "github.com/micro/go-micro/server"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ client.Option
var _ server.Option

// Client API for CreateStoreService service

type CreateStoreService interface {
	CreateStore(ctx context.Context, in *CreateStoreParam, opts ...client.CallOption) (*CreateStoreResponse, error)
}

type createStoreService struct {
	c    client.Client
	name string
}

func NewCreateStoreService(name string, c client.Client) CreateStoreService {
	if c == nil {
		c = client.NewClient()
	}
	if len(name) == 0 {
		name = "go.micro.storeservice"
	}
	return &createStoreService{
		c:    c,
		name: name,
	}
}

func (c *createStoreService) CreateStore(ctx context.Context, in *CreateStoreParam, opts ...client.CallOption) (*CreateStoreResponse, error) {
	req := c.c.NewRequest(c.name, "CreateStoreService.CreateStore", in)
	out := new(CreateStoreResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for CreateStoreService service

type CreateStoreServiceHandler interface {
	CreateStore(context.Context, *CreateStoreParam, *CreateStoreResponse) error
}

func RegisterCreateStoreServiceHandler(s server.Server, hdlr CreateStoreServiceHandler, opts ...server.HandlerOption) error {
	type createStoreService interface {
		CreateStore(ctx context.Context, in *CreateStoreParam, out *CreateStoreResponse) error
	}
	type CreateStoreService struct {
		createStoreService
	}
	h := &createStoreServiceHandler{hdlr}
	return s.Handle(s.NewHandler(&CreateStoreService{h}, opts...))
}

type createStoreServiceHandler struct {
	CreateStoreServiceHandler
}

func (h *createStoreServiceHandler) CreateStore(ctx context.Context, in *CreateStoreParam, out *CreateStoreResponse) error {
	return h.CreateStoreServiceHandler.CreateStore(ctx, in, out)
}
