// Code generated by protoc-gen-go. DO NOT EDIT.
// source: proto/store/store.proto

package go_micro_storeservice

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type CreateStoreParam struct {
	Store                string   `protobuf:"bytes,1,opt,name=store,proto3" json:"store,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateStoreParam) Reset()         { *m = CreateStoreParam{} }
func (m *CreateStoreParam) String() string { return proto.CompactTextString(m) }
func (*CreateStoreParam) ProtoMessage()    {}
func (*CreateStoreParam) Descriptor() ([]byte, []int) {
	return fileDescriptor_81990e9044344d76, []int{0}
}

func (m *CreateStoreParam) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateStoreParam.Unmarshal(m, b)
}
func (m *CreateStoreParam) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateStoreParam.Marshal(b, m, deterministic)
}
func (m *CreateStoreParam) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateStoreParam.Merge(m, src)
}
func (m *CreateStoreParam) XXX_Size() int {
	return xxx_messageInfo_CreateStoreParam.Size(m)
}
func (m *CreateStoreParam) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateStoreParam.DiscardUnknown(m)
}

var xxx_messageInfo_CreateStoreParam proto.InternalMessageInfo

func (m *CreateStoreParam) GetStore() string {
	if m != nil {
		return m.Store
	}
	return ""
}

type CreateStoreResponse struct {
	Result               string   `protobuf:"bytes,2,opt,name=result,proto3" json:"result,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateStoreResponse) Reset()         { *m = CreateStoreResponse{} }
func (m *CreateStoreResponse) String() string { return proto.CompactTextString(m) }
func (*CreateStoreResponse) ProtoMessage()    {}
func (*CreateStoreResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_81990e9044344d76, []int{1}
}

func (m *CreateStoreResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateStoreResponse.Unmarshal(m, b)
}
func (m *CreateStoreResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateStoreResponse.Marshal(b, m, deterministic)
}
func (m *CreateStoreResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateStoreResponse.Merge(m, src)
}
func (m *CreateStoreResponse) XXX_Size() int {
	return xxx_messageInfo_CreateStoreResponse.Size(m)
}
func (m *CreateStoreResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateStoreResponse.DiscardUnknown(m)
}

var xxx_messageInfo_CreateStoreResponse proto.InternalMessageInfo

func (m *CreateStoreResponse) GetResult() string {
	if m != nil {
		return m.Result
	}
	return ""
}

func init() {
	proto.RegisterType((*CreateStoreParam)(nil), "go.micro.storeservice.CreateStoreParam")
	proto.RegisterType((*CreateStoreResponse)(nil), "go.micro.storeservice.CreateStoreResponse")
}

func init() { proto.RegisterFile("proto/store/store.proto", fileDescriptor_81990e9044344d76) }

var fileDescriptor_81990e9044344d76 = []byte{
	// 162 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x12, 0x2f, 0x28, 0xca, 0x2f,
	0xc9, 0xd7, 0x2f, 0x2e, 0xc9, 0x2f, 0x4a, 0x85, 0x90, 0x7a, 0x60, 0x11, 0x21, 0xd1, 0xf4, 0x7c,
	0xbd, 0xdc, 0xcc, 0xe4, 0xa2, 0x7c, 0x3d, 0xb0, 0x68, 0x71, 0x6a, 0x51, 0x59, 0x66, 0x72, 0xaa,
	0x92, 0x06, 0x97, 0x80, 0x73, 0x51, 0x6a, 0x62, 0x49, 0x6a, 0x30, 0x48, 0x34, 0x20, 0xb1, 0x28,
	0x31, 0x57, 0x48, 0x84, 0x8b, 0x15, 0xac, 0x46, 0x82, 0x51, 0x81, 0x51, 0x83, 0x33, 0x08, 0xc2,
	0x51, 0xd2, 0xe5, 0x12, 0x46, 0x52, 0x19, 0x94, 0x5a, 0x5c, 0x90, 0x9f, 0x57, 0x9c, 0x2a, 0x24,
	0xc6, 0xc5, 0x56, 0x94, 0x5a, 0x5c, 0x9a, 0x53, 0x22, 0xc1, 0x04, 0x56, 0x0d, 0xe5, 0x19, 0x55,
	0x71, 0x09, 0x21, 0x29, 0x0f, 0x86, 0x58, 0x27, 0x94, 0xc2, 0xc5, 0x8d, 0x24, 0x2a, 0xa4, 0xae,
	0x87, 0xd5, 0x55, 0x7a, 0xe8, 0x4e, 0x92, 0xd2, 0x22, 0xac, 0x10, 0xe6, 0x22, 0x25, 0x86, 0x24,
	0x36, 0xb0, 0x97, 0x8d, 0x01, 0x01, 0x00, 0x00, 0xff, 0xff, 0x25, 0xe4, 0x0b, 0x81, 0x0d, 0x01,
	0x00, 0x00,
}
