// Code generated by protoc-gen-go. DO NOT EDIT.
// source: proto/message.proto

package go_micro_messageservice

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type PushMessageToUserParam struct {
	Content              string   `protobuf:"bytes,1,opt,name=content,proto3" json:"content,omitempty"`
	ReceiverId           string   `protobuf:"bytes,2,opt,name=receiverId,proto3" json:"receiverId,omitempty"`
	ActionUrl            string   `protobuf:"bytes,3,opt,name=actionUrl,proto3" json:"actionUrl,omitempty"`
	Type                 string   `protobuf:"bytes,4,opt,name=type,proto3" json:"type,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PushMessageToUserParam) Reset()         { *m = PushMessageToUserParam{} }
func (m *PushMessageToUserParam) String() string { return proto.CompactTextString(m) }
func (*PushMessageToUserParam) ProtoMessage()    {}
func (*PushMessageToUserParam) Descriptor() ([]byte, []int) {
	return fileDescriptor_33f3a5e1293a7bcd, []int{0}
}

func (m *PushMessageToUserParam) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PushMessageToUserParam.Unmarshal(m, b)
}
func (m *PushMessageToUserParam) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PushMessageToUserParam.Marshal(b, m, deterministic)
}
func (m *PushMessageToUserParam) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PushMessageToUserParam.Merge(m, src)
}
func (m *PushMessageToUserParam) XXX_Size() int {
	return xxx_messageInfo_PushMessageToUserParam.Size(m)
}
func (m *PushMessageToUserParam) XXX_DiscardUnknown() {
	xxx_messageInfo_PushMessageToUserParam.DiscardUnknown(m)
}

var xxx_messageInfo_PushMessageToUserParam proto.InternalMessageInfo

func (m *PushMessageToUserParam) GetContent() string {
	if m != nil {
		return m.Content
	}
	return ""
}

func (m *PushMessageToUserParam) GetReceiverId() string {
	if m != nil {
		return m.ReceiverId
	}
	return ""
}

func (m *PushMessageToUserParam) GetActionUrl() string {
	if m != nil {
		return m.ActionUrl
	}
	return ""
}

func (m *PushMessageToUserParam) GetType() string {
	if m != nil {
		return m.Type
	}
	return ""
}

type PushMessageToUserResponse struct {
	Result               string   `protobuf:"bytes,5,opt,name=result,proto3" json:"result,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PushMessageToUserResponse) Reset()         { *m = PushMessageToUserResponse{} }
func (m *PushMessageToUserResponse) String() string { return proto.CompactTextString(m) }
func (*PushMessageToUserResponse) ProtoMessage()    {}
func (*PushMessageToUserResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_33f3a5e1293a7bcd, []int{1}
}

func (m *PushMessageToUserResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PushMessageToUserResponse.Unmarshal(m, b)
}
func (m *PushMessageToUserResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PushMessageToUserResponse.Marshal(b, m, deterministic)
}
func (m *PushMessageToUserResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PushMessageToUserResponse.Merge(m, src)
}
func (m *PushMessageToUserResponse) XXX_Size() int {
	return xxx_messageInfo_PushMessageToUserResponse.Size(m)
}
func (m *PushMessageToUserResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_PushMessageToUserResponse.DiscardUnknown(m)
}

var xxx_messageInfo_PushMessageToUserResponse proto.InternalMessageInfo

func (m *PushMessageToUserResponse) GetResult() string {
	if m != nil {
		return m.Result
	}
	return ""
}

type JumpUrlWithKeyAndParamsParam struct {
	Key                  string            `protobuf:"bytes,6,opt,name=key,proto3" json:"key,omitempty"`
	Map                  map[string]string `protobuf:"bytes,7,rep,name=map,proto3" json:"map,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *JumpUrlWithKeyAndParamsParam) Reset()         { *m = JumpUrlWithKeyAndParamsParam{} }
func (m *JumpUrlWithKeyAndParamsParam) String() string { return proto.CompactTextString(m) }
func (*JumpUrlWithKeyAndParamsParam) ProtoMessage()    {}
func (*JumpUrlWithKeyAndParamsParam) Descriptor() ([]byte, []int) {
	return fileDescriptor_33f3a5e1293a7bcd, []int{2}
}

func (m *JumpUrlWithKeyAndParamsParam) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_JumpUrlWithKeyAndParamsParam.Unmarshal(m, b)
}
func (m *JumpUrlWithKeyAndParamsParam) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_JumpUrlWithKeyAndParamsParam.Marshal(b, m, deterministic)
}
func (m *JumpUrlWithKeyAndParamsParam) XXX_Merge(src proto.Message) {
	xxx_messageInfo_JumpUrlWithKeyAndParamsParam.Merge(m, src)
}
func (m *JumpUrlWithKeyAndParamsParam) XXX_Size() int {
	return xxx_messageInfo_JumpUrlWithKeyAndParamsParam.Size(m)
}
func (m *JumpUrlWithKeyAndParamsParam) XXX_DiscardUnknown() {
	xxx_messageInfo_JumpUrlWithKeyAndParamsParam.DiscardUnknown(m)
}

var xxx_messageInfo_JumpUrlWithKeyAndParamsParam proto.InternalMessageInfo

func (m *JumpUrlWithKeyAndParamsParam) GetKey() string {
	if m != nil {
		return m.Key
	}
	return ""
}

func (m *JumpUrlWithKeyAndParamsParam) GetMap() map[string]string {
	if m != nil {
		return m.Map
	}
	return nil
}

type JumpUrlWithKeyAndParamsResponse struct {
	UrlStr               string   `protobuf:"bytes,8,opt,name=urlStr,proto3" json:"urlStr,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *JumpUrlWithKeyAndParamsResponse) Reset()         { *m = JumpUrlWithKeyAndParamsResponse{} }
func (m *JumpUrlWithKeyAndParamsResponse) String() string { return proto.CompactTextString(m) }
func (*JumpUrlWithKeyAndParamsResponse) ProtoMessage()    {}
func (*JumpUrlWithKeyAndParamsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_33f3a5e1293a7bcd, []int{3}
}

func (m *JumpUrlWithKeyAndParamsResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_JumpUrlWithKeyAndParamsResponse.Unmarshal(m, b)
}
func (m *JumpUrlWithKeyAndParamsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_JumpUrlWithKeyAndParamsResponse.Marshal(b, m, deterministic)
}
func (m *JumpUrlWithKeyAndParamsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_JumpUrlWithKeyAndParamsResponse.Merge(m, src)
}
func (m *JumpUrlWithKeyAndParamsResponse) XXX_Size() int {
	return xxx_messageInfo_JumpUrlWithKeyAndParamsResponse.Size(m)
}
func (m *JumpUrlWithKeyAndParamsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_JumpUrlWithKeyAndParamsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_JumpUrlWithKeyAndParamsResponse proto.InternalMessageInfo

func (m *JumpUrlWithKeyAndParamsResponse) GetUrlStr() string {
	if m != nil {
		return m.UrlStr
	}
	return ""
}

func init() {
	proto.RegisterType((*PushMessageToUserParam)(nil), "go.micro.messageservice.PushMessageToUserParam")
	proto.RegisterType((*PushMessageToUserResponse)(nil), "go.micro.messageservice.PushMessageToUserResponse")
	proto.RegisterType((*JumpUrlWithKeyAndParamsParam)(nil), "go.micro.messageservice.JumpUrlWithKeyAndParamsParam")
	proto.RegisterMapType((map[string]string)(nil), "go.micro.messageservice.JumpUrlWithKeyAndParamsParam.MapEntry")
	proto.RegisterType((*JumpUrlWithKeyAndParamsResponse)(nil), "go.micro.messageservice.JumpUrlWithKeyAndParamsResponse")
}

func init() { proto.RegisterFile("proto/message.proto", fileDescriptor_33f3a5e1293a7bcd) }

var fileDescriptor_33f3a5e1293a7bcd = []byte{
	// 359 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x9c, 0x53, 0x4d, 0x4f, 0xc2, 0x40,
	0x14, 0x74, 0x29, 0x9f, 0xcf, 0x8b, 0xae, 0x06, 0x56, 0x42, 0x90, 0xf4, 0xc4, 0xa9, 0x24, 0x25,
	0x1a, 0xf4, 0x60, 0xe2, 0xc1, 0x83, 0x1a, 0x12, 0x02, 0x12, 0xcf, 0xb5, 0xbc, 0x40, 0x63, 0xdb,
	0x6d, 0x76, 0xb7, 0x24, 0xf5, 0xec, 0xd1, 0xb3, 0x7f, 0xc3, 0xbb, 0xbf, 0xce, 0xb0, 0xa5, 0x81,
	0x04, 0x6b, 0xd4, 0xdb, 0xce, 0x4c, 0x67, 0xdf, 0xcc, 0xdb, 0x14, 0x8e, 0x22, 0xc1, 0x15, 0xef,
	0x05, 0x28, 0xa5, 0x33, 0x47, 0x4b, 0x23, 0xda, 0x98, 0x73, 0x2b, 0xf0, 0x5c, 0xc1, 0xad, 0x35,
	0x2f, 0x51, 0x2c, 0x3d, 0x17, 0xcd, 0x57, 0x02, 0xf5, 0x51, 0x2c, 0x17, 0xc3, 0x94, 0x7e, 0xe0,
	0x53, 0x89, 0x62, 0xe4, 0x08, 0x27, 0xa0, 0x0c, 0x2a, 0x2e, 0x0f, 0x15, 0x86, 0x8a, 0x91, 0x0e,
	0xe9, 0xd6, 0xc6, 0x19, 0xa4, 0x6d, 0x00, 0x81, 0x2e, 0x7a, 0x4b, 0x14, 0xb7, 0x33, 0x56, 0xd0,
	0xe2, 0x16, 0x43, 0x5b, 0x50, 0x73, 0x5c, 0xe5, 0xf1, 0x70, 0x2a, 0x7c, 0x66, 0x68, 0x79, 0x43,
	0x50, 0x0a, 0x45, 0x95, 0x44, 0xc8, 0x8a, 0x5a, 0xd0, 0x67, 0xb3, 0x0f, 0x27, 0x3b, 0x29, 0xc6,
	0x28, 0x23, 0x1e, 0x4a, 0xa4, 0x75, 0x28, 0x0b, 0x94, 0xb1, 0xaf, 0x58, 0x49, 0x5b, 0xd6, 0xc8,
	0xfc, 0x24, 0xd0, 0xba, 0x8b, 0x83, 0x68, 0x2a, 0xfc, 0x47, 0x4f, 0x2d, 0xee, 0x31, 0xb9, 0x0e,
	0x67, 0x3a, 0xbb, 0x4c, 0x1b, 0x1c, 0x80, 0xf1, 0x8c, 0x09, 0x2b, 0x6b, 0xd7, 0xea, 0x48, 0x47,
	0x60, 0x04, 0x4e, 0xc4, 0x2a, 0x1d, 0xa3, 0xbb, 0x6f, 0x5f, 0x59, 0x39, 0x5b, 0xb1, 0x7e, 0xba,
	0xd5, 0x1a, 0x3a, 0xd1, 0x4d, 0xa8, 0x44, 0x32, 0x5e, 0x5d, 0xd5, 0x3c, 0x87, 0x6a, 0x46, 0x64,
	0xf3, 0xc8, 0x66, 0xde, 0x31, 0x94, 0x96, 0x8e, 0x1f, 0xe3, 0x7a, 0x49, 0x29, 0xb8, 0x2c, 0x0c,
	0x88, 0x79, 0x01, 0xa7, 0x39, 0x53, 0xb6, 0x7b, 0xc7, 0xc2, 0x9f, 0x28, 0xc1, 0xaa, 0x69, 0xef,
	0x14, 0xd9, 0xef, 0x04, 0xd8, 0xce, 0xb6, 0x26, 0x69, 0x74, 0xfa, 0x02, 0x87, 0x3b, 0x1a, 0xed,
	0xe5, 0x36, 0xfd, 0xfe, 0xed, 0x9b, 0xf6, 0xef, 0x0d, 0x59, 0x5c, 0x73, 0xcf, 0xfe, 0x20, 0xd0,
	0xce, 0x29, 0x95, 0xc5, 0x7b, 0x23, 0xd0, 0xc8, 0xf9, 0x84, 0x9e, 0xfd, 0xeb, 0x3d, 0x9a, 0x83,
	0xbf, 0xda, 0x36, 0x89, 0x9f, 0xca, 0xfa, 0xf7, 0xe8, 0x7f, 0x05, 0x00, 0x00, 0xff, 0xff, 0xa0,
	0xbb, 0xff, 0x2e, 0x35, 0x03, 0x00, 0x00,
}
