// Code generated by protoc-gen-micro. DO NOT EDIT.
// source: socketMessage.proto

package go_micro_socketMessageservice

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

import (
	context "context"
	client "github.com/micro/go-micro/client"
	server "github.com/micro/go-micro/server"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ client.Option
var _ server.Option

// Client API for PushSocketMessageToUserService service

type PushSocketMessageToUserService interface {
	PushMessageSocketToUser(ctx context.Context, in *PushSocketMessageToUserParam, opts ...client.CallOption) (*PushSocketMessageToUserResponse, error)
}

type pushSocketMessageToUserService struct {
	c    client.Client
	name string
}

func NewPushSocketMessageToUserService(name string, c client.Client) PushSocketMessageToUserService {
	if c == nil {
		c = client.NewClient()
	}
	if len(name) == 0 {
		name = "go.micro.socketMessageservice"
	}
	return &pushSocketMessageToUserService{
		c:    c,
		name: name,
	}
}

func (c *pushSocketMessageToUserService) PushMessageSocketToUser(ctx context.Context, in *PushSocketMessageToUserParam, opts ...client.CallOption) (*PushSocketMessageToUserResponse, error) {
	req := c.c.NewRequest(c.name, "PushSocketMessageToUserService.PushMessageSocketToUser", in)
	out := new(PushSocketMessageToUserResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for PushSocketMessageToUserService service

type PushSocketMessageToUserServiceHandler interface {
	PushMessageSocketToUser(context.Context, *PushSocketMessageToUserParam, *PushSocketMessageToUserResponse) error
}

func RegisterPushSocketMessageToUserServiceHandler(s server.Server, hdlr PushSocketMessageToUserServiceHandler, opts ...server.HandlerOption) error {
	type pushSocketMessageToUserService interface {
		PushMessageSocketToUser(ctx context.Context, in *PushSocketMessageToUserParam, out *PushSocketMessageToUserResponse) error
	}
	type PushSocketMessageToUserService struct {
		pushSocketMessageToUserService
	}
	h := &pushSocketMessageToUserServiceHandler{hdlr}
	return s.Handle(s.NewHandler(&PushSocketMessageToUserService{h}, opts...))
}

type pushSocketMessageToUserServiceHandler struct {
	PushSocketMessageToUserServiceHandler
}

func (h *pushSocketMessageToUserServiceHandler) PushMessageSocketToUser(ctx context.Context, in *PushSocketMessageToUserParam, out *PushSocketMessageToUserResponse) error {
	return h.PushSocketMessageToUserServiceHandler.PushMessageSocketToUser(ctx, in, out)
}
