// Code generated by protoc-gen-go. DO NOT EDIT.
// source: proto/share/share.proto

package go_micro_videoservice

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type CreateShareParam struct {
	LastAuthorId         int64    `protobuf:"varint,1,opt,name=lastAuthorId,proto3" json:"lastAuthorId,omitempty"`
	AuthorId             int64    `protobuf:"varint,2,opt,name=authorId,proto3" json:"authorId,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateShareParam) Reset()         { *m = CreateShareParam{} }
func (m *CreateShareParam) String() string { return proto.CompactTextString(m) }
func (*CreateShareParam) ProtoMessage()    {}
func (*CreateShareParam) Descriptor() ([]byte, []int) {
	return fileDescriptor_a91733f900302165, []int{0}
}

func (m *CreateShareParam) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateShareParam.Unmarshal(m, b)
}
func (m *CreateShareParam) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateShareParam.Marshal(b, m, deterministic)
}
func (m *CreateShareParam) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateShareParam.Merge(m, src)
}
func (m *CreateShareParam) XXX_Size() int {
	return xxx_messageInfo_CreateShareParam.Size(m)
}
func (m *CreateShareParam) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateShareParam.DiscardUnknown(m)
}

var xxx_messageInfo_CreateShareParam proto.InternalMessageInfo

func (m *CreateShareParam) GetLastAuthorId() int64 {
	if m != nil {
		return m.LastAuthorId
	}
	return 0
}

func (m *CreateShareParam) GetAuthorId() int64 {
	if m != nil {
		return m.AuthorId
	}
	return 0
}

type CreateShareResponse struct {
	Result               string   `protobuf:"bytes,3,opt,name=result,proto3" json:"result,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateShareResponse) Reset()         { *m = CreateShareResponse{} }
func (m *CreateShareResponse) String() string { return proto.CompactTextString(m) }
func (*CreateShareResponse) ProtoMessage()    {}
func (*CreateShareResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_a91733f900302165, []int{1}
}

func (m *CreateShareResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateShareResponse.Unmarshal(m, b)
}
func (m *CreateShareResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateShareResponse.Marshal(b, m, deterministic)
}
func (m *CreateShareResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateShareResponse.Merge(m, src)
}
func (m *CreateShareResponse) XXX_Size() int {
	return xxx_messageInfo_CreateShareResponse.Size(m)
}
func (m *CreateShareResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateShareResponse.DiscardUnknown(m)
}

var xxx_messageInfo_CreateShareResponse proto.InternalMessageInfo

func (m *CreateShareResponse) GetResult() string {
	if m != nil {
		return m.Result
	}
	return ""
}

func init() {
	proto.RegisterType((*CreateShareParam)(nil), "go.micro.videoservice.CreateShareParam")
	proto.RegisterType((*CreateShareResponse)(nil), "go.micro.videoservice.CreateShareResponse")
}

func init() { proto.RegisterFile("proto/share/share.proto", fileDescriptor_a91733f900302165) }

var fileDescriptor_a91733f900302165 = []byte{
	// 190 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x12, 0x2f, 0x28, 0xca, 0x2f,
	0xc9, 0xd7, 0x2f, 0xce, 0x48, 0x2c, 0x4a, 0x85, 0x90, 0x7a, 0x60, 0x11, 0x21, 0xd1, 0xf4, 0x7c,
	0xbd, 0xdc, 0xcc, 0xe4, 0xa2, 0x7c, 0xbd, 0xb2, 0xcc, 0x94, 0xd4, 0xfc, 0xe2, 0xd4, 0xa2, 0xb2,
	0xcc, 0xe4, 0x54, 0xa5, 0x20, 0x2e, 0x01, 0xe7, 0xa2, 0xd4, 0xc4, 0x92, 0xd4, 0x60, 0x90, 0xda,
	0x80, 0xc4, 0xa2, 0xc4, 0x5c, 0x21, 0x25, 0x2e, 0x9e, 0x9c, 0xc4, 0xe2, 0x12, 0xc7, 0xd2, 0x92,
	0x8c, 0xfc, 0x22, 0xcf, 0x14, 0x09, 0x46, 0x05, 0x46, 0x0d, 0xe6, 0x20, 0x14, 0x31, 0x21, 0x29,
	0x2e, 0x8e, 0x44, 0x98, 0x3c, 0x13, 0x58, 0x1e, 0xce, 0x57, 0xd2, 0xe5, 0x12, 0x46, 0x32, 0x33,
	0x28, 0xb5, 0xb8, 0x20, 0x3f, 0xaf, 0x38, 0x55, 0x48, 0x8c, 0x8b, 0xad, 0x28, 0xb5, 0xb8, 0x34,
	0xa7, 0x44, 0x82, 0x59, 0x81, 0x51, 0x83, 0x33, 0x08, 0xca, 0x33, 0xaa, 0xe2, 0x12, 0x42, 0x52,
	0x1e, 0x0c, 0x71, 0x98, 0x50, 0x0a, 0x17, 0x37, 0x92, 0xa8, 0x90, 0xba, 0x1e, 0x56, 0xf7, 0xeb,
	0xa1, 0x3b, 0x5e, 0x4a, 0x8b, 0xb0, 0x42, 0x98, 0x8b, 0x94, 0x18, 0x92, 0xd8, 0xc0, 0x81, 0x63,
	0x0c, 0x08, 0x00, 0x00, 0xff, 0xff, 0x94, 0x9a, 0x96, 0xaa, 0x37, 0x01, 0x00, 0x00,
}
