// Code generated by protoc-gen-go. DO NOT EDIT.
// source: socketMessage.proto

package go_micro_socketMessageservice

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type PushSocketMessageToUserParam struct {
	Content              string   `protobuf:"bytes,1,opt,name=content,proto3" json:"content,omitempty"`
	ReceiverId           string   `protobuf:"bytes,2,opt,name=receiverId,proto3" json:"receiverId,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PushSocketMessageToUserParam) Reset()         { *m = PushSocketMessageToUserParam{} }
func (m *PushSocketMessageToUserParam) String() string { return proto.CompactTextString(m) }
func (*PushSocketMessageToUserParam) ProtoMessage()    {}
func (*PushSocketMessageToUserParam) Descriptor() ([]byte, []int) {
	return fileDescriptor_bddba5bc21c22695, []int{0}
}

func (m *PushSocketMessageToUserParam) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PushSocketMessageToUserParam.Unmarshal(m, b)
}
func (m *PushSocketMessageToUserParam) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PushSocketMessageToUserParam.Marshal(b, m, deterministic)
}
func (m *PushSocketMessageToUserParam) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PushSocketMessageToUserParam.Merge(m, src)
}
func (m *PushSocketMessageToUserParam) XXX_Size() int {
	return xxx_messageInfo_PushSocketMessageToUserParam.Size(m)
}
func (m *PushSocketMessageToUserParam) XXX_DiscardUnknown() {
	xxx_messageInfo_PushSocketMessageToUserParam.DiscardUnknown(m)
}

var xxx_messageInfo_PushSocketMessageToUserParam proto.InternalMessageInfo

func (m *PushSocketMessageToUserParam) GetContent() string {
	if m != nil {
		return m.Content
	}
	return ""
}

func (m *PushSocketMessageToUserParam) GetReceiverId() string {
	if m != nil {
		return m.ReceiverId
	}
	return ""
}

type PushSocketMessageToUserResponse struct {
	Result               string   `protobuf:"bytes,5,opt,name=result,proto3" json:"result,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PushSocketMessageToUserResponse) Reset()         { *m = PushSocketMessageToUserResponse{} }
func (m *PushSocketMessageToUserResponse) String() string { return proto.CompactTextString(m) }
func (*PushSocketMessageToUserResponse) ProtoMessage()    {}
func (*PushSocketMessageToUserResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_bddba5bc21c22695, []int{1}
}

func (m *PushSocketMessageToUserResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PushSocketMessageToUserResponse.Unmarshal(m, b)
}
func (m *PushSocketMessageToUserResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PushSocketMessageToUserResponse.Marshal(b, m, deterministic)
}
func (m *PushSocketMessageToUserResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PushSocketMessageToUserResponse.Merge(m, src)
}
func (m *PushSocketMessageToUserResponse) XXX_Size() int {
	return xxx_messageInfo_PushSocketMessageToUserResponse.Size(m)
}
func (m *PushSocketMessageToUserResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_PushSocketMessageToUserResponse.DiscardUnknown(m)
}

var xxx_messageInfo_PushSocketMessageToUserResponse proto.InternalMessageInfo

func (m *PushSocketMessageToUserResponse) GetResult() string {
	if m != nil {
		return m.Result
	}
	return ""
}

func init() {
	proto.RegisterType((*PushSocketMessageToUserParam)(nil), "go.micro.socketMessageservice.PushSocketMessageToUserParam")
	proto.RegisterType((*PushSocketMessageToUserResponse)(nil), "go.micro.socketMessageservice.PushSocketMessageToUserResponse")
}

func init() { proto.RegisterFile("socketMessage.proto", fileDescriptor_bddba5bc21c22695) }

var fileDescriptor_bddba5bc21c22695 = []byte{
	// 203 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x12, 0x2e, 0xce, 0x4f, 0xce,
	0x4e, 0x2d, 0xf1, 0x4d, 0x2d, 0x2e, 0x4e, 0x4c, 0x4f, 0xd5, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17,
	0x92, 0x4d, 0xcf, 0xd7, 0xcb, 0xcd, 0x4c, 0x2e, 0xca, 0xd7, 0x43, 0x91, 0x2d, 0x4e, 0x2d, 0x2a,
	0xcb, 0x4c, 0x4e, 0x55, 0x8a, 0xe0, 0x92, 0x09, 0x28, 0x2d, 0xce, 0x08, 0x46, 0x96, 0x0b, 0xc9,
	0x0f, 0x2d, 0x4e, 0x2d, 0x0a, 0x48, 0x2c, 0x4a, 0xcc, 0x15, 0x92, 0xe0, 0x62, 0x4f, 0xce, 0xcf,
	0x2b, 0x49, 0xcd, 0x2b, 0x91, 0x60, 0x54, 0x60, 0xd4, 0xe0, 0x0c, 0x82, 0x71, 0x85, 0xe4, 0xb8,
	0xb8, 0x8a, 0x52, 0x93, 0x53, 0x33, 0xcb, 0x52, 0x8b, 0x3c, 0x53, 0x24, 0x98, 0xc0, 0x92, 0x48,
	0x22, 0x4a, 0x96, 0x5c, 0xf2, 0x38, 0x4c, 0x0e, 0x4a, 0x2d, 0x2e, 0xc8, 0xcf, 0x2b, 0x4e, 0x15,
	0x12, 0xe3, 0x62, 0x2b, 0x4a, 0x2d, 0x2e, 0xcd, 0x29, 0x91, 0x60, 0x05, 0x6b, 0x87, 0xf2, 0x8c,
	0x76, 0x33, 0x72, 0xc9, 0xe1, 0xd0, 0x1b, 0x0c, 0x71, 0xb7, 0xd0, 0x0c, 0x46, 0x2e, 0x71, 0x90,
	0x12, 0xa8, 0x24, 0x44, 0x25, 0x44, 0x89, 0x90, 0xb5, 0x1e, 0x5e, 0x3f, 0xeb, 0xe1, 0xf3, 0xb0,
	0x94, 0x1d, 0x79, 0x9a, 0x61, 0x7e, 0x52, 0x62, 0x48, 0x62, 0x03, 0x07, 0xbc, 0x31, 0x20, 0x00,
	0x00, 0xff, 0xff, 0xf3, 0xf8, 0xdd, 0xc8, 0x8f, 0x01, 0x00, 0x00,
}
