// Code generated by protoc-gen-micro. DO NOT EDIT.
// source: proto/addStoreCourse/addStoreCourse.proto

package go_micro_storeservice

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

import (
	context "context"
	client "github.com/micro/go-micro/client"
	server "github.com/micro/go-micro/server"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ client.Option
var _ server.Option

// Client API for AddStoreCourseService service

type AddStoreCourseService interface {
	AddStoreCourse(ctx context.Context, in *AddStoreCourseParam, opts ...client.CallOption) (*AddStoreCourseResponse, error)
}

type addStoreCourseService struct {
	c    client.Client
	name string
}

func NewAddStoreCourseService(name string, c client.Client) AddStoreCourseService {
	if c == nil {
		c = client.NewClient()
	}
	if len(name) == 0 {
		name = "go.micro.storeservice"
	}
	return &addStoreCourseService{
		c:    c,
		name: name,
	}
}

func (c *addStoreCourseService) AddStoreCourse(ctx context.Context, in *AddStoreCourseParam, opts ...client.CallOption) (*AddStoreCourseResponse, error) {
	req := c.c.NewRequest(c.name, "AddStoreCourseService.AddStoreCourse", in)
	out := new(AddStoreCourseResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for AddStoreCourseService service

type AddStoreCourseServiceHandler interface {
	AddStoreCourse(context.Context, *AddStoreCourseParam, *AddStoreCourseResponse) error
}

func RegisterAddStoreCourseServiceHandler(s server.Server, hdlr AddStoreCourseServiceHandler, opts ...server.HandlerOption) error {
	type addStoreCourseService interface {
		AddStoreCourse(ctx context.Context, in *AddStoreCourseParam, out *AddStoreCourseResponse) error
	}
	type AddStoreCourseService struct {
		addStoreCourseService
	}
	h := &addStoreCourseServiceHandler{hdlr}
	return s.Handle(s.NewHandler(&AddStoreCourseService{h}, opts...))
}

type addStoreCourseServiceHandler struct {
	AddStoreCourseServiceHandler
}

func (h *addStoreCourseServiceHandler) AddStoreCourse(ctx context.Context, in *AddStoreCourseParam, out *AddStoreCourseResponse) error {
	return h.AddStoreCourseServiceHandler.AddStoreCourse(ctx, in, out)
}
