// Code generated by protoc-gen-go. DO NOT EDIT.
// source: proto/addStoreCourse/addStoreCourse.proto

package go_micro_storeservice

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type AddStoreCourseParam struct {
	AuthorId             int64    `protobuf:"varint,1,opt,name=authorId,proto3" json:"authorId,omitempty"`
	CourseId             int64    `protobuf:"varint,2,opt,name=courseId,proto3" json:"courseId,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AddStoreCourseParam) Reset()         { *m = AddStoreCourseParam{} }
func (m *AddStoreCourseParam) String() string { return proto.CompactTextString(m) }
func (*AddStoreCourseParam) ProtoMessage()    {}
func (*AddStoreCourseParam) Descriptor() ([]byte, []int) {
	return fileDescriptor_a8045b339bb27be3, []int{0}
}

func (m *AddStoreCourseParam) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AddStoreCourseParam.Unmarshal(m, b)
}
func (m *AddStoreCourseParam) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AddStoreCourseParam.Marshal(b, m, deterministic)
}
func (m *AddStoreCourseParam) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AddStoreCourseParam.Merge(m, src)
}
func (m *AddStoreCourseParam) XXX_Size() int {
	return xxx_messageInfo_AddStoreCourseParam.Size(m)
}
func (m *AddStoreCourseParam) XXX_DiscardUnknown() {
	xxx_messageInfo_AddStoreCourseParam.DiscardUnknown(m)
}

var xxx_messageInfo_AddStoreCourseParam proto.InternalMessageInfo

func (m *AddStoreCourseParam) GetAuthorId() int64 {
	if m != nil {
		return m.AuthorId
	}
	return 0
}

func (m *AddStoreCourseParam) GetCourseId() int64 {
	if m != nil {
		return m.CourseId
	}
	return 0
}

type AddStoreCourseResponse struct {
	Result               string   `protobuf:"bytes,3,opt,name=result,proto3" json:"result,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AddStoreCourseResponse) Reset()         { *m = AddStoreCourseResponse{} }
func (m *AddStoreCourseResponse) String() string { return proto.CompactTextString(m) }
func (*AddStoreCourseResponse) ProtoMessage()    {}
func (*AddStoreCourseResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_a8045b339bb27be3, []int{1}
}

func (m *AddStoreCourseResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AddStoreCourseResponse.Unmarshal(m, b)
}
func (m *AddStoreCourseResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AddStoreCourseResponse.Marshal(b, m, deterministic)
}
func (m *AddStoreCourseResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AddStoreCourseResponse.Merge(m, src)
}
func (m *AddStoreCourseResponse) XXX_Size() int {
	return xxx_messageInfo_AddStoreCourseResponse.Size(m)
}
func (m *AddStoreCourseResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_AddStoreCourseResponse.DiscardUnknown(m)
}

var xxx_messageInfo_AddStoreCourseResponse proto.InternalMessageInfo

func (m *AddStoreCourseResponse) GetResult() string {
	if m != nil {
		return m.Result
	}
	return ""
}

func init() {
	proto.RegisterType((*AddStoreCourseParam)(nil), "go.micro.storeservice.AddStoreCourseParam")
	proto.RegisterType((*AddStoreCourseResponse)(nil), "go.micro.storeservice.AddStoreCourseResponse")
}

func init() {
	proto.RegisterFile("proto/addStoreCourse/addStoreCourse.proto", fileDescriptor_a8045b339bb27be3)
}

var fileDescriptor_a8045b339bb27be3 = []byte{
	// 190 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xd2, 0x2c, 0x28, 0xca, 0x2f,
	0xc9, 0xd7, 0x4f, 0x4c, 0x49, 0x09, 0x2e, 0xc9, 0x2f, 0x4a, 0x75, 0xce, 0x2f, 0x2d, 0x2a, 0x4e,
	0x45, 0xe3, 0xea, 0x81, 0xd5, 0x08, 0x89, 0xa6, 0xe7, 0xeb, 0xe5, 0x66, 0x26, 0x17, 0xe5, 0xeb,
	0x15, 0x83, 0xe4, 0x8a, 0x53, 0x8b, 0xca, 0x32, 0x93, 0x53, 0x95, 0x7c, 0xb9, 0x84, 0x1d, 0x51,
	0x94, 0x07, 0x24, 0x16, 0x25, 0xe6, 0x0a, 0x49, 0x71, 0x71, 0x24, 0x96, 0x96, 0x64, 0xe4, 0x17,
	0x79, 0xa6, 0x48, 0x30, 0x2a, 0x30, 0x6a, 0x30, 0x07, 0xc1, 0xf9, 0x20, 0xb9, 0x64, 0xb0, 0x52,
	0xcf, 0x14, 0x09, 0x26, 0x88, 0x1c, 0x8c, 0xaf, 0x64, 0xc0, 0x25, 0x86, 0x6a, 0x5c, 0x50, 0x6a,
	0x71, 0x41, 0x7e, 0x5e, 0x71, 0xaa, 0x90, 0x18, 0x17, 0x5b, 0x51, 0x6a, 0x71, 0x69, 0x4e, 0x89,
	0x04, 0xb3, 0x02, 0xa3, 0x06, 0x67, 0x10, 0x94, 0x67, 0xd4, 0xc6, 0xc8, 0x25, 0x8a, 0xaa, 0x25,
	0x18, 0xe2, 0x34, 0xa1, 0x5c, 0x2e, 0x3e, 0x54, 0x09, 0x21, 0x2d, 0x3d, 0xac, 0x9e, 0xd0, 0xc3,
	0xe2, 0x03, 0x29, 0x5d, 0xa2, 0xd4, 0xc2, 0x9c, 0xa7, 0xc4, 0x90, 0xc4, 0x06, 0x0e, 0x27, 0x63,
	0x40, 0x00, 0x00, 0x00, 0xff, 0xff, 0x62, 0x41, 0xca, 0x0e, 0x54, 0x01, 0x00, 0x00,
}
